language: go
sudo: required
services:
  - docker
go: 
  - "1.10.x"
script:
  - echo "GETTING TO COMMAND **"
  - docker images
  - git submodule update --init 
  - which make
  - go get github.com/cpuguy83/go-md2man > log.text
  - make build TARGET=centos7 VERSIONS=8 >> log.text
  - mkdir extract; cd extract
  - docker save centos/s2i-base-centos7 > test.tar
  - tar xvf test.tar >> log.text
  - cp ../test.sh .
  - sh ./test.sh >> log.text
  - docker images  
  - find . -name package.json -print
  - curl -v google.com  
  - filename=./862a73efea0f888bd4b6fa16ee12fef5cd2bd6b46e4bab9638d248b5f0cc1219/opt/rh/rh-nodejs8/root/usr/lib/node_modules/npm/package.json
  - curl -F"manifest[]=@$filename" -F"filePath[]=/home/JohnDoe" http://bayesian-api-schoudhu-fabric8-analytics.dev.rdu2c.fabric8.io/api/v1/application-analysis
 
  
  
  
  
  
  
