name: Container-tests by GitHub Action at Testing Farm

on:
  issue_comment:
    types:
      - created
jobs:
  build:
    # This job only runs for '[test]' pull request comments by owner, member
    name: Container-tests by GitHub Action on Testing Farm service
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - tmt_plan: "fedora"
            os_test: "fedora"
            context: "Fedora"
            compose: "CentOS-7"
            api_key: "TF_PUBLIC_API_KEY"
            branch: "main"
            tmt_repo: "https://github.com/sclorg/sclorg-testing-farm"
          - tmt_plan: "centos7"
            os_test: "centos7"
            context: "CentOS7"
            compose: "CentOS-7"
            api_key: "TF_PUBLIC_API_KEY"
            branch: "main"
            tmt_repo: "https://github.com/sclorg/sclorg-testing-farm"
          - tmt_plan: "rhel7-docker"
            os_test: "rhel7"
            context: "RHEL7"
            compose: "RHEL-7.9-Released"
            api_key: "TF_INTERNAL_API_KEY"
            branch: "master"
            tmt_repo: "https://gitlab.cee.redhat.com/platform-eng-core-services/sclorg-tmt-plans"
          - tmt_plan: "rhel8-docker"
            os_test: "rhel8"
            context: "RHEL8"
            compose: "RHEL-8.3.1-Released"
            api_key: "TF_INTERNAL_API_KEY"
            branch: "master"
            tmt_repo: "https://gitlab.cee.redhat.com/platform-eng-core-services/sclorg-tmt-plans"
          - tmt_plan: "c9s"
            os_test: "c9s"
            context: "CentOS Stream 9"
            compose: "CentOS-Stream-9"
            api_key: "TF_PUBLIC_API_KEY"
            branch: "main"
            tmt_repo: "https://github.com/sclorg/sclorg-testing-farm"

    if: |
      github.event.issue.pull_request
      && (contains(github.event.comment.body, '[test]') || contains(github.event.comment.body, '[test-all]'))
      && contains(fromJson('["OWNER", "MEMBER"]'), github.event.comment.author_association)
    steps:
      - name: Get pull request number
        id: pr_nr
        run: |
          PR_URL="${{ github.event.comment.issue_url }}"
          echo "::set-output name=PR_NR::${PR_URL##*/}"

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: "refs/pull/${{ steps.pr_nr.outputs.PR_NR }}/head"

      # https://github.com/sclorg/testing-farm-as-github-action
      - name: Schedule tests on external Testing Farm by Testing-Farm-as-github-action
        id: github_action
        uses: sclorg/testing-farm-as-github-action@v1
        with:
          api_key: ${{ secrets[matrix.api_key] }}
          git_url: ${{ matrix.tmt_repo }}
          git_ref: ${{ matrix.branch }}
          tmt_plan_regex: ${{ matrix.tmt_plan }}
          pull_request_status_name: ${{ matrix.context }}
          variables: "REPO_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY;REPO_NAME=$GITHUB_REPOSITORY;PR_NUMBER=${{ steps.pr_nr.outputs.PR_NR }};OS=${{ matrix.os_test }};TEST_NAME=test"
          compose: ${{ matrix.compose }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
